### ISSUE TITLE
"Invalid data" error: MXF/JPEG2000 and uncompressed

### ISSUE THREAD

**Issue by GregH18** [amiaopensource/vrecord#208] opened 2017-12-15 21:11 UTC
One more issue. We captured a video using an MXF container and JPEG2000 video codec, but we receive the "Invalid data" error message below. We're also having trouble with MXF/Uncompressed also. Can anyone confirm these problems?

![image04](https://user-images.githubusercontent.com/27779274/33963857-7ff8b782-e024-11e7-8b93-bcb45e5eed94.png)

**Comment by retokromer** [comment] 2017-12-20 17:42
Did anyone reproduce this?

**Comment by retokromer** [comment] 2018-01-03 16:51
@GregH18 Which version of vrecord are you running? (The command `vrecord -h` prints the installed version.)

**Comment by bturkus** [comment] 2018-01-08 19:24
hi @retokromer. Sorry for not getting back you sooner about this, but I'm seeing the error on vrecord 2018-01-05. 

When I run ```vrecord -h```, I get the following:
```
'vrecord 2017-06-15 ( /vrecord/2017-07-15 ( /vrecord/2017-07-27 ( /vrecord/2017-10-17 ( /vrecord/2017-12-15 ( /vrecord/2018-01-05
```
Do you know what all of this means, and is it a prob in any way?

**Comment by retokromer** [comment] 2018-01-08 19:50
@bturkus What is your output of `brew info vrecord`?

**Comment by bturkus** [comment] 2018-01-08 20:12
I was able to reproduce the error, for both jpeg200 and uncompressed. And here's what brew info says:

```
amiaopensource/amiaos/vrecord: stable 2018-01-05, HEAD
Capturing a video signal and turning it into a digital file
https://github.com/amiaopensource/vrecord
/usr/local/Cellar/vrecord/2017-06-15 (6 files, 136.9KB)
  Built from source on 2017-06-15 at 12:01:52
/usr/local/Cellar/vrecord/2017-07-15 (6 files, 137.0KB)
  Built from source on 2017-07-19 at 15:17:04
/usr/local/Cellar/vrecord/2017-07-27 (6 files, 137.3KB)
  Built from source on 2017-07-28 at 13:32:49
/usr/local/Cellar/vrecord/2017-10-17 (6 files, 135KB)
  Built from source on 2017-12-08 at 10:10:05
/usr/local/Cellar/vrecord/2017-12-15 (6 files, 134.8KB)
  Built from source on 2017-12-15 at 12:40:49
/usr/local/Cellar/vrecord/2018-01-05 (6 files, 135KB) *
  Built from source on 2018-01-08 at 13:36:09
From: https://github.com/amiaopensource/homebrew-amiaos/blob/master/vrecord.rb
==> Dependencies
Required: sdl ✔, cowsay ✔, freetype ✔, amiaopensource/amiaos/decklinksdk ✔, amiaopensource/amiaos/ffmpegdecklink --with-sdl2 --with-freetype ✔, mpv ✔, qcli ✔
Recommended: xmlstarlet ✔
==> Options
--without-xmlstarlet
	Build without xmlstarlet support
--HEAD
	Install HEAD version
```

**Comment by retokromer** [comment] 2018-01-08 20:27
Thank you very much, @bturkus! I will modify the grep in order to catch only the line with `*`, the actually installed.

And thank you as well for checking! I will try to delve into this.

**Comment by dericed** [comment] 2018-01-08 21:55
for original issue, this is either fixed by changing:
`middleoptions+=(-c:v libopenjpeg)`

to
`middleoptions+=(-c:v jpeg2000)`

or by adding --with-libopenjpeg to the installation requirements. Probably worth testing the two to see which encoder can best sustain real time capture.

**Comment by retokromer** [comment] 2018-01-09 06:06
I will delve in my notes, because at least one is broken (I guess openjpeg).

**Comment by retokromer** [comment] 2018-01-09 06:27
As long as I know, OpenJPEG is still broken: lossless means a little lossy! Probably the error is there since the beginning. The error is publically known since more than three years now.

Currently we use internally Grok, but this cannot be compiled easily with a Brew formula.

@dericed: What is the status of jpeg2000?

**Comment by retokromer** [comment] 2018-01-09 08:05
Here the information: According to my two years old notes, `libopenjpeg` is 6–7 times faster and the files are 25% bigger in comparison to `jpeg2000`. That’s the reason why we would like to use `libopenjpeg`… if there wasn’t the little rounding error.

Does `jpeg2000` encode also in 10 bit or is it designed only for 8 bit?

I will open a PR with `libopenjpeg`.

**Comment by dericed** [comment] 2018-01-09 21:22
Also possible to allow both options:
- jpeg2000 (FFmpeg)
- jpeg2000 (libopenjpeg)

**Comment by retokromer** [comment] 2018-01-10 08:18
@dericed: Do you think it would be better with both options? I’ve to admit that I’m a little skeptical.

As said above, on one hand, `libopenjpeg` seem now to be fixed and, on the other hand, I do ignore the status of `jpeg2000`. Was/is it broken as well?

Yet, I guess more importantly, when I check:
```
ffmpeg -h encoder=jpeg2000
```
I got:
```
Encoder jpeg2000 [JPEG 2000]:
    General capabilities: none
    Threading capabilities: none
    Supported pixel formats: rgb24 yuv444p gray yuv420p yuv422p yuv410p yuv411p
```
Are those pixel formats not all 8 bit only?

**Comment by dericed** [comment] 2018-01-10 13:42
I forgot how limiting that jpeg2000 encoder was. In this case, yes listing only libopenjpeg seems fine. thx

**Comment by retokromer** [comment] 2018-01-10 14:07
Thank you for confirming! Then all is fine!

**Closed by retokromer** 2018-01-10 14:07 UTC
Labels: bug
