### ISSUE TITLE
embedded pal ffv1/mkv mediaconch fail

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#349] opened 2018-06-28 17:58 UTC
hi,
I'd love confirmation of this, but we're noticing that PAL ffv1/mkvs with embedded logs seem to be failing the built-in mediaconch test. We're not seeing this embedded ntscs, and I'm generally confused about why the files are failing. vrecord reports this:

![pal fail](https://user-images.githubusercontent.com/8987230/42051777-ef52e034-7ada-11e8-8528-a09f6e800f31.jpeg)
But the files themselves seem to be fine when tested in mediaconch proper:

![screen shot 2018-06-28 at 1 42 56 pm](https://user-images.githubusercontent.com/8987230/42051826-116ed420-7adb-11e8-8e53-839f1e5d95cf.png)

And this may be overkill, but here's the full xml produced by vrecord:
```
<?xml version="1.0" encoding="UTF-8"?>
<MediaConch xmlns="https://mediaarea.net/mediaconch" xmlns:mmt="https://mediaarea.net/micromediatrace" xmlns:mi="https://mediaarea.net/mediainfo" version="0.3">
  <media ref="/Volumes/NYPL_15905/2018_084_pami_090_wilson1/embed_test_pal_ffv1.mkv">
    <policy name="Check validity of FFV1 Matroska and Quicktime files" type="and" rules_run="22" fail_count="1" pass_count="21" outcome="fail">
      <description>This policy tests FFV1 Matroska and Quicktime files made using vrecord and checks their validity</description>
      <rule name="Is the video format FFV1?" value="Format" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Format='FFV1'" outcome="pass"/>
      <rule name="FFV1 is version 3.4 or later?" value="Format_Version" tracktype="Video" occurrence="*" operator="&gt;=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Format_Version&gt;='3.4'" outcome="pass"/>
      <rule name="FFV1 is encoded in GOP size of 1?" value="Format_Settings_GOP" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Format_Settings_GOP='N=1'" outcome="pass"/>
      <rule name="Is the display aspect ratio 1.333?" value="DisplayAspectRatio" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:DisplayAspectRatio='1.333'" outcome="pass"/>
      <rule name="Is the frame rate mode constant?" value="FrameRate_Mode" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate_Mode='CFR'" outcome="pass"/>
      <rule name="Is the color space YUV?" value="ColorSpace" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:ColorSpace='YUV'" outcome="pass"/>
      <rule name="Is the chroma subsampling 4:2:2?" value="ChromaSubsampling" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:ChromaSubsampling='4:2:2'" outcome="pass"/>
      <rule name="Is the video interlaced?" value="ScanType" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:ScanType='Interlaced'" outcome="pass"/>
      <rule name="Is the compression mode lossless?" value="Compression_Mode" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Compression_Mode='Lossless'" outcome="pass"/>
      <rule name="Is max slice count at least 4?" value="extra/MaxSlicesCount" tracktype="Video" occurrence="*" operator="&gt;=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:extra/mi:MaxSlicesCount&gt;='4'" outcome="pass"/>
      <rule name="Is error detection type per slice?" value="extra/ErrorDetectionType" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:extra/mi:ErrorDetectionType='Per slice'" outcome="pass"/>
      <rule name="Is the video stream first?" value="StreamOrder" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:StreamOrder='0'" outcome="pass"/>
      <rule name="Is the colour description present?" value="colour_description_present" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:colour_description_present='Yes'" outcome="pass"/>
      <rule name="Are the transfer characteristics BT.709?" value="transfer_characteristics" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:transfer_characteristics='BT.709'" outcome="pass"/>
      <rule name="Is the audio stream on track 2?" value="StreamOrder" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:StreamOrder='1'" outcome="pass"/>
      <rule name="Is the audio PCM?" value="Format" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:Format='PCM'" outcome="pass"/>
      <rule name="Is the audio bit depth 24?" value="BitDepth" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:BitDepth='24'" outcome="pass"/>
      <rule name="Is the sample rate 48kHz?" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:SamplingRate='48000'" outcome="pass"/>
      <policy name="Is the container Matroska or Quicktime?" type="or" rules_run="2" fail_count="2" pass_count="0" outcome="fail">
        <policy name="Is it good Matroska?" type="and" rules_run="3" fail_count="1" pass_count="2" outcome="fail">
          <policy name="Is it new Matroska with an UUID?" type="and" rules_run="5" fail_count="0" pass_count="5" outcome="pass">
            <rule name="Is it Matroska?" value="Format" tracktype="General" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='General'][*]/mi:Format='Matroska'" outcome="pass"/>
            <rule name="Matroska version 4 or greater?" value="Format_Version" tracktype="General" occurrence="*" operator="&gt;=" xpath="mi:MediaInfo/mi:track[@type='General'][*]/mi:Format_Version&gt;='4'" outcome="pass"/>
            <rule name="Unique ID is present?" value="UniqueID" tracktype="General" occurrence="*" xpath="mi:MediaInfo/mi:track[@type='General'][*]/mi:UniqueID" outcome="pass"/>
            <rule name="Is the FFV1 Codec ID V_MS/VFW/FOURCC / FFV1?" value="CodecID" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:CodecID='V_MS/VFW/FOURCC / FFV1'" outcome="pass"/>
            <rule name="Is the PCM Codec ID A_PCM/INT/LIT" value="CodecID" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:CodecID='A_PCM/INT/LIT'" outcome="pass"/>
          </policy>
          <policy name="Is it NTSC SD or PAL SD?" type="or" rules_run="2" fail_count="2" pass_count="0" outcome="fail">
            <description>Quick test for NTSC vs Pal to validate matrix coefficients. Full NTSC vs PAL test below</description>
            <policy name="Is it NTSC?" type="and" rules_run="1" fail_count="1" pass_count="0" outcome="fail">
              <rule name="NTSC FrameRate 29.970?" value="FrameRate" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate='29.970'" actual="25.000" outcome="fail"/>
            </policy>
            <policy name="Is it PAL?" type="and" rules_run="2" fail_count="1" pass_count="1" outcome="fail">
              <description>The PAL matrix coefficients value is reported differently depending on container. This test validates for Matroska</description>
              <rule name="PAL FrameRate 25.000?" value="FrameRate" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate='25.000'" outcome="pass"/>
              <rule name="Are the matrix coefficients BT.470 System B, BT.470 System G?" value="matrix_coefficients" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:matrix_coefficients='BT.470 System B, BT.470 System G'" actual="BT.470 System B/G" outcome="fail"/>
            </policy>
          </policy>
          <policy name="Has Matroska finished writing?" type="and" rules_run="4" fail_count="0" pass_count="4" outcome="pass">
            <rule name="Duration is greater than zero?" scope="mmt" value="Segment/Info/Duration/Data" occurrence="*" operator="&gt;" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='Info']/mmt:b[@n='Duration']/mmt:d&gt;'0'" outcome="pass"/>
            <rule name="SeekHead is present?" scope="mmt" value="Segment/SeekHead/" occurrence="*" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='SeekHead']" outcome="pass"/>
            <rule name="Cues is present?" scope="mmt" value="Segment/Cues/" occurrence="*" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='Cues']" outcome="pass"/>
            <policy name="Select Top-Level Elements have CRCs?" type="and" rules_run="6" fail_count="0" pass_count="6" outcome="pass">
              <rule name="SeekHead CRC-32 is present?" scope="mmt" value="Segment/SeekHead/CRC-32/" occurrence="*" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='SeekHead']/mmt:b[@n='CRC-32']" outcome="pass"/>
              <rule name="Info CRC-32 is present?" scope="mmt" value="Segment/Info/CRC-32/" occurrence="*" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='Info']/mmt:b[@n='CRC-32']" outcome="pass"/>
              <rule name="Tracks CRC-32 is present?" scope="mmt" value="Segment/Tracks/CRC-32/" occurrence="*" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='Tracks']/mmt:b[@n='CRC-32']" outcome="pass"/>
              <rule name="Cluster CRC-32 is present?" scope="mmt" value="Segment/Cluster/CRC-32/" occurrence="*" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='Cluster']/mmt:b[@n='CRC-32']" outcome="pass"/>
              <rule name="Cues CRC-32 is present?" scope="mmt" value="Segment/Cues/CRC-32/" occurrence="*" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='Cues']/mmt:b[@n='CRC-32']" outcome="pass"/>
              <rule name="Tags CRC-32 is present?" scope="mmt" value="Segment/Tags/CRC-32/" occurrence="*" xpath="mmt:MicroMediaTrace/mmt:b[@n='Segment']/mmt:b[@n='Tags']/mmt:b[@n='CRC-32']" outcome="pass"/>
            </policy>
          </policy>
        </policy>
        <policy name="Is it good Quicktime?" type="and" rules_run="8" fail_count="8" pass_count="0" outcome="fail">
          <rule name="Is the file extension mov?" value="FileExtension" tracktype="General" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='General'][*]/mi:FileExtension='mov'" actual="mkv" outcome="fail"/>
          <rule name="Is the format MPEG-4?" value="Format" tracktype="General" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='General'][*]/mi:Format='MPEG-4'" actual="Matroska" outcome="fail"/>
          <rule name="Is the format profile QuickTime?" value="Format_Profile" tracktype="General" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='General'][*]/mi:Format_Profile='QuickTime'" actual="" outcome="fail"/>
          <rule name="Is the FFV1 Codec ID FFV1?" value="CodecID" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:CodecID='FFV1'" actual="V_MS/VFW/FOURCC / FFV1" outcome="fail"/>
          <rule name="Is the PCM Codec ID in24?" value="CodecID" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:CodecID='in24'" actual="A_PCM/INT/LIT" outcome="fail"/>
          <rule name="Is the endianness Little?" value="Format_Settings_Endianness" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:Format_Settings_Endianness='Little'" actual="" outcome="fail"/>
          <rule name="Is the signedness signed?" value="Format_Settings_Sign" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:Format_Settings_Sign='Signed'" actual="" outcome="fail"/>
          <policy name="Is it NTSC SD or PAL SD?" type="or" rules_run="2" fail_count="2" pass_count="0" outcome="fail">
            <policy name="Is it NTSC?" type="and" rules_run="1" fail_count="1" pass_count="0" outcome="fail">
              <rule name="NTSC FrameRate 29.970?" value="FrameRate" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate='29.970'" actual="25.000" outcome="fail"/>
            </policy>
            <policy name="Is it PAL?" type="and" rules_run="2" fail_count="1" pass_count="1" outcome="fail">
              <description>The PAL matrix coefficients value is reported differently depending on container. This test validates for Quicktime</description>
              <rule name="PAL FrameRate 25.000?" value="FrameRate" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate='25.000'" outcome="pass"/>
              <rule name="Are the matrix coefficients BT.601?" value="matrix_coefficients" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:matrix_coefficients='BT.601'" actual="BT.470 System B/G" outcome="fail"/>
            </policy>
          </policy>
        </policy>
      </policy>
      <policy name="Is the video bit depth 8 or 10?" type="or" rules_run="2" fail_count="1" pass_count="1" outcome="pass">
        <rule name="Is the video bit depth 8?" value="BitDepth" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:BitDepth='8'" actual="10" outcome="fail"/>
        <rule name="Is the video bit depth 10?" value="BitDepth" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:BitDepth='10'" outcome="pass"/>
      </policy>
      <policy name="Is it NTSC SD or PAL SD?" type="or" rules_run="2" fail_count="1" pass_count="1" outcome="pass">
        <policy name="Is it NTSC?" type="and" rules_run="7" fail_count="6" pass_count="1" outcome="fail">
          <rule name="NTSC height 486?" value="Height" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Height='486'" actual="576" outcome="fail"/>
          <rule name="NTSC width 720?" value="Width" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Width='720'" outcome="pass"/>
          <rule name="NTSC FrameRate 29.970?" value="FrameRate" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate='29.970'" actual="25.000" outcome="fail"/>
          <rule name="NTSC pixel aspect ratio 0.900?" value="PixelAspectRatio" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:PixelAspectRatio='0.900'" actual="1.067" outcome="fail"/>
          <rule name="NTSC scan order bottom field first?" value="ScanOrder" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:ScanOrder='BFF'" actual="TFF" outcome="fail"/>
          <rule name="NTSC colour primaries BT.601 NTSC?" value="colour_primaries" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:colour_primaries='BT.601 NTSC'" actual="BT.601 PAL" outcome="fail"/>
          <rule name="Are the matrix coefficients BT.601?" value="matrix_coefficients" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:matrix_coefficients='BT.601'" actual="BT.470 System B/G" outcome="fail"/>
        </policy>
        <policy name="Is it PAL?" type="and" rules_run="6" fail_count="0" pass_count="6" outcome="pass">
          <rule name="PAL height 576?" value="Height" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Height='576'" outcome="pass"/>
          <rule name="PAL Width 720?" value="Width" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:Width='720'" outcome="pass"/>
          <rule name="PAL FrameRate 25.000?" value="FrameRate" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:FrameRate='25.000'" outcome="pass"/>
          <rule name="PAL pixel aspect ratio 1.067?" value="PixelAspectRatio" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:PixelAspectRatio='1.067'" outcome="pass"/>
          <rule name="PAL scan order top field first?" value="ScanOrder" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:ScanOrder='TFF'" outcome="pass"/>
          <rule name="PAL colour primaries BT.601 PAL?" value="colour_primaries" tracktype="Video" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Video'][*]/mi:colour_primaries='BT.601 PAL'" outcome="pass"/>
        </policy>
      </policy>
      <policy name="1 or 2 channels of audio?" type="or" rules_run="2" fail_count="1" pass_count="1" outcome="pass">
        <rule name="1 channel of audio?" value="Channels" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:Channels='1'" actual="2" outcome="fail"/>
        <rule name="2 channels of audio?" value="Channels" tracktype="Audio" occurrence="*" operator="=" xpath="mi:MediaInfo/mi:track[@type='Audio'][*]/mi:Channels='2'" outcome="pass"/>
      </policy>
    </policy>
  </media>
</MediaConch>
```

**Comment by dericed** [comment] 2018-06-28 18:04
This is a regression since https://github.com/MediaArea/MediaInfoLib/commit/c75a5f3a864c92ee472b706ba362677f5f0a4697 as @jeromemartinez changed the corresponding expression for PAL's colorspace in this case.

**Comment by dericed** [comment] 2018-06-28 18:05
https://github.com/amiaopensource/vrecord/pull/350 should resolve but I haven't tested

**Comment by dericed** [comment] 2018-07-02 23:28
resolved in https://github.com/amiaopensource/vrecord/pull/350

**Closed by dericed** 2018-07-02 23:28 UTC
