### ISSUE TITLE
vrecord not writing seekhead

### ISSUE THREAD

**Issue by beccabender** [amiaopensource/vrecord#228] opened 2018-01-10 20:49 UTC
I'm using the newly updated vrecord, and when I stop recording by doing a window close, the seek head is not written into the file - see below mkvalidator report.

If I put in a duration to stop the recording, then the file is fine.

Thanks!

TSOA0643-1WK-O8:~ Station2$ mkvalidator /Volumes/MIAP_Projects_RAID/Becca/vrecordtest_002_ffv1.mkv 
WRN801: The segment has no SeekHead section                   
WRN0C2: The timecode of the Cluster at 403157 is not incrementing (may be intentional)
WRN800: The segment has Clusters but no Cues section (bad for seeking)
mkvalidator 0.5.2: the file appears to be valid

**Comment by dericed** [comment] 2018-01-10 20:59
ffmpeg is not finishing wriitng the file correctly as ffplay is closed, the writing simply stops. As a result vrecord would also not be able to make a valid quicktime file. As a antidote to a capture Matroska, run `mkclean file.mkv`. To get vrecord to end a file correctly the duration setting could be used to stop ffmpeg via the duration limit rather than by closing the window.

**Comment by dericed** [comment] 2018-01-10 21:36
A simpler way to reproduce the issue is with:
`ffmpeg -f lavfi -i testsrc -c:v ffv1 test.mov -c:v ffv1 -f nut - | ffplay -`

The video will play in ffplay, but when you close the window to stop ffplay, ffmpeg will crash and not finish writing the file, resulting in an invalid quicktime.

**Comment by bturkus** [comment] 2018-01-10 21:47
fascinating. so if capturing to mkv and regularly finishing up captures by closing the ffplay window, would it be a good idea to have a batch cleaning? 

I guess my real question is: are seek heads critical, or more of a boutique feature? I've always kind of thought of them (and cues) as relevant only if we were marking the content in some meaningful way.

**Comment by dericed** [comment] 2018-01-10 21:49
seek heads and cues are important for navigating the file efficiently, you should check your files with mkvalidator or mediaconch.

**Comment by dericed** [comment] 2018-01-10 21:49
also note that in this scenario
`ffmpeg -y -f lavfi -i testsrc -c:v ffv1 -f matroska - | tee >(ffplay -) | ffmpeg -y -i - -c:v copy test.mov`

the ffplay window can be closed and test.mov will be valid, but this needs 2 ffmpegs

**Comment by retokromer** [comment] 2018-01-11 13:26
`test.mkv` ;-)

**Comment by dericed** [comment] 2018-01-11 13:35
The issue is more apparent with mov since there will be no moov atom. Mkv is resilient enough to still function even without cues or seekhead.

**Comment by retokromer** [comment] 2018-01-11 13:39
On my side, with `.mov` it encodes wrong also in the last scenario:
```
[matroska,webm @ 0x7fae03802a00] Read error
pipe:: Function not implemented
```

**Closed** 2018-01-11 21:22 UTC
Labels: the sky is falling
